### ISSUE TITLE
As a user, I want to notify all lowest administrative areas when I report or update an event

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/ewea#72]
### Tasks
- [ ] Find all lowest administrative areas from the current administrative area
- [ ] Include them on notification criteria
- [ ] Support simple flags on event to always notify everyone in case is needed
- [ ] Support `notifyAll` on `EventType`
