### ISSUE TITLE
As a coordinator, I want close an event so that i can mark its end

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/ewea#74]
### Tasks
- [ ] Set `endedAt` when end event via `changelog API`
- [ ] Notify stakeholder on end of event
- [ ] Remind coordinator on ending event

### Exception
- [ ] Is event re-open allowed?
